baseURL = "https://www.colebrooke.org/"
languageCode = "en-us"
title = "Colebrooke, Coleford & Penstone in Devon"
theme = "notrack"
newContentEditor = "remarkable"
mainSections = ["blog"]
# disqusShortname = "colebrooke"
paginate = 4

[params]
  author = "Neville Enderson, John Enderson"
  siteHeading = "The Parish of Colebrooke, Devon" # defaults to author
  Description = "Discover Colebrooke Parish, a charming group of villages in Devon, known for its historical landmarks, beautiful countryside."
  
  showBlogLatest = true
  mainSections = ["blog"]
  showTaxonomyLinks = false
  nBlogLatest = 4 # number of blog post om the home page
  blogLatestHeading = "Latest.."

  [params.social]
    email = ""
    facebook = "colebrookeparish"

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
